In [1]:
import pandas as pd
import numpy as np

In [2]:
flood_data = pd.read_csv("./kenya_western/flood_history/ke_western_flood_data.csv")
flood_data.head()

,Unnamed: 0,field_1,Id,Dis No,Year,Seq,Glide,Disaster Group,Disaster Subgroup,Disaster Type,...,engtype_2,cc_2,hasc_2,bbox,centroid,area,area_ha,gid_0,LONGIT,LATIT\
0,153,1530,1876,2011-0504-KEN,2011,504,FL-2011-000184,Natural,Hydrological,Flood,...,Constituency,201,NaN,"{""type"":""Polygon"",""coordinates"":[[[34.70991516...","{""type"":""Point"",""coordinates"":[34.834418947283...",425732270.4,42285.54467,KEN,34.834419,0.455657
1,154,1531,2658,2020-0164-KEN,2020,164,NaN,Natural,Hydrological,Flood,...,Constituency,201,NaN,"{""type"":""Polygon"",""coordinates"":[[[34.70991516...","{""type"":""Point"",""coordinates"":[34.834418947283...",425732270.4,42285.54467,KEN,34.834419,0.455657
2,158,1474,2158,2015-0564-KEN,2015,564,FL-2015-000169,Natural,Hydrological,Flood,...,Constituency,223,NaN,"{""type"":""Polygon"",""coordinates"":[[[34.64166641...","{""type"":""Point"",""coordinates"":[34.733406158189...",178728431.8,17749.86849,KEN,34.733406,0.789089
3,337,2249,1895,2011-0504-KEN,2011,504,FL-2011-000184,Natural,Hydrological,Flood,...,Constituency,264,NaN,"{""type"":""Polygon"",""coordinates"":[[[34.71281433...","{""type"":""Point"",""coordinates"":[34.808592792652...",242245370.0,24057.40432,KEN,34.808593,0.826858
4,338,2250,2183,2015-0159-KEN,2015,159,FL-2015-000049,Natural,Hydrological,Flood,...,Constituency,264,NaN,"{""type"":""Polygon"",""coordinates"":[[[34.71281433...","{""type"":""Point"",""coordinates"":[34.808592792652...",242245370.0,24057.40432,KEN,34.808593,0.826858

In [5]:
for i in flood_data.iterrows():
    print(i["LONGIT"])

TypeError: tuple indices must be integers or slices, not str

In [7]:
flood_data

NameError: name 'size' is not defined